extends:
  - recommended

rules:
  operation-operationId-unique:
    severity: warn

  path-not-include-query:
    severity: warn

  no-path-trailing-slash:
    severity: warn

  operation-4xx-response:
    severity: warn

  spec:
    severity: warn

  info-license:
    severity: off
