name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: redocly openapi lint
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm i @redocly/cli@latest
      - run: redocly lint openapi.json
